s3_conf:
  access_key: AKIAVTS7F7LCWXEGTSVC
  secret_access_key: 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

sftp_conf:
  hostname: ec2-34-245-189-229.eu-west-1.compute.amazonaws.com
  port: 22
  username: ubuntu
  pem: spark.pem

mysql_conf:
  hostname: testdb.csazqwmdry0b.eu-west-1.rds.amazonaws.com
  port: 3306
  database: testdb
  username: master
  password: Temp1234

mongodb_config:
  uri: mongodb://ec2-3-250-61-179.eu-west-1.compute.amazonaws.com:27017

redshift_conf:
  host: test.cpetdpdf4jxg.eu-west-1.redshift.amazonaws.com
  port: 5439
  database: dev
  username: master
  password: Temp1234